Ask user to share after having an experiment installed for 3 days (closes #1097).
mozilla/testpilot pull request #1292
Opened 2016-08-25 23:14 UTC by chuckharmston

r?

2016-08-25 23:25 UTC, chuckharmston commented
NB: for users who already have Test Pilot + experiments installed, this will only trigger 3 days after the *next* experiment is installed.

It wasn't specced, but as a one-time measure to bridge that gap, we could toss this tab to any users who have experiments installed when they receive this update. I'm going to build this and we can back it out if it's not desired.

2016-08-25 23:55 UTC, chuckharmston commented
The above is now reflected in the code. Additionally, I set the timeout to 1 second, rather than 3 days, in all non-production environments to make for easier testing.

2016-08-26 00:19 UTC, chuckharmston commented
Also updated so that the onboarding tab and share tab never open simultaneously, giving priority to the former.

2016-08-29 16:09 UTC, lmorchard commented
Will take a look at this today, too

2016-08-29 18:30 UTC, lmorchard commented
Would be very handy to have unit tests for this stuff, now that we have the capability

2016-08-29 18:50 UTC, lmorchard commented on addon/index.js
> +    typeof store.showSharePromptAt === 'undefined' && hasExperimentInstalled()
Trying to work though the logic here to make sure I've got it right... Looks like there are 2 cases when the share-solicitation tab gets shown:

1. Existing Test Pilot users with at least one experiment installed will see a sharing-solicitation immediately on their next browser restart.

2. Future Test Pilot users on their first experiment enable will get a sharing-solicitation scheduled for the next browser restart after at least 3 days have passed.

In either of these cases, `store.showSharePromptAt` gets set to `false` after showing the tab. That, in turn, records that the tab has been shown and no future showings will be scheduled on experiment enables.

As long as I've got all that right, I'd say case 1 sounds okay if we assume existing Test Pilot users have had an experiment around for more than 3 days, so this is basically playing catch-up.

2016-08-29 18:51 UTC, lmorchard commented
Okay, basically three nits:

1. This stuff would be great if it lived in its own submodule in `lib/` with associated unit tests. (So we don't add to #610)
1. We should probably delete `store.showSharePromptAt` on uninstall. We're not consistent about it, but we've started adding [cleanup-on-uninstall code](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L28) in spots to make uninstall / reinstall behavior more consistent. 
1. Might be clearer if `store.showSharePromptAt` got split into 2 properties instead of doing double duty - i.e. as a datestamp to schedule the next solicitation showing, while also serving as a marker that the tab was shown via being undefined / being assigned `false`

2016-09-07 18:16 UTC, meandavejustice commented
I am unable to test this because of a [seemingly unrelated issue](https://github.com/mozilla/testpilot/issues/1324) But this looks good to me. It has my 👍 so long as @lmorchard 's comments are addressed

2016-09-16 04:28 UTC, chuckharmston commented
@lmorchard Your comments should all be addressed. I refactored this enough that it probably warrants a re-review.

2016-09-16 05:26 UTC, chuckharmston commented
@ckprice mind reviewing the instrumentation? Everything in #1099 should be here except for the actual logging of the pageview, which I've omitted due to #1362.

2016-09-16 19:54 UTC, lmorchard commented on addon/lib/share-prompt.js
> + /*
:+1: yay modularization!

2016-09-16 19:54 UTC, lmorchard commented on addon/test/test-share-prompt.js
> +/*
:+1: yay tests!

2016-09-16 19:56 UTC, lmorchard commented on docs/metrics/ga.md
> +| Click on a button in the Share section                   | ShareView Interactions             | button click             | {facebook,twitter,email,copy} |
:+1: yay doco!

2016-09-16 19:56 UTC, lmorchard commented on docs/metrics/ga.md
> +| Home Page, Experiment Detail Page, Share Page | Does the user have the add-on installed           | 1         | {0,1}  |
:+1: yay more doco!

2016-09-16 20:04 UTC, lmorchard commented on addon/test/test-share-prompt.js
> +/*
:+1: and tests pass with `jpm test --verbose --binary /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin`

2016-09-16 20:09 UTC, lmorchard commented on addon/lib/share-prompt.js
> +    delete store.sharePrompt;
Hmm, you probably want to move this into an `uninstall` method and only call in `onUnload` when [`reason` is `uninstall`](https://github.com/chuckharmston/testpilot/blob/e41ddb458c7b16edb37988ef3ce35311c9d9da04/addon/index.js#L381). 

Doing this on all `onUnload` cases [includes `shutdown`, `upgrade`, and `downgrade`](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Listening_for_load_and_unload#exports.onUnload()). That means you'll delete your tracking state on every browser shutdown or add-on upgrade and forget you already showed the prompt.

In retrospect, I think `destroy` is a terrible name for this pattern in the add-on modules :/ `teardown` might be better.

2016-09-16 20:15 UTC, lmorchard requested changes
Looks good except for the one kink I saw with `onUnload` and `destroy`.

2016-09-16 20:19 UTC, ckprice approved these changes
Approving the collections part of this. Everything in #1099 (minus the `pageview` calls as you mentioned) LGTM 👍  Events are firing, and shared URL's have the proper campaign tags.

2016-09-16 20:47 UTC, dannycoates commented on addon/lib/share-prompt.js
> +    delete store.sharePrompt;
All the data in `store` gets deleted anyway on uninstall, right? I'd suggest just removing `destroy` altogether.

2016-09-16 21:23 UTC, lmorchard commented on addon/lib/share-prompt.js
> +    delete store.sharePrompt;
No, it doesn't, and that's one of our ongoing issues. The SDK doesn't auto-delete the data in store. So, if you uninstall our add-on, it sticks around. If you re-install, you don't get a clean slate.

2016-09-17 00:44 UTC, dannycoates commented on addon/lib/share-prompt.js
> +    delete store.sharePrompt;
> The SDK doesn't auto-delete the data in store

Oh interesting... That's not the behavior I've observed on another addon. 🤔

2016-09-17 22:55 UTC, chuckharmston commented on addon/lib/share-prompt.js
> +    delete store.sharePrompt;
That's a really good catch. Good call, @lmorchard.

2016-09-17 23:13 UTC, chuckharmston commented
@ckprice It may be worth trying to get https://mzl.la URLs for each different share URL, since they're long and sort of ugly with the `utm_`s. That domain is administered as a custom bit.ly domain for `mozilla.org`. Since we're on `firefox.com`, we'd need an administrator for the bit.ly account to create them manually. Maybe you know who to talk to about that?

2016-09-17 23:57 UTC, chuckharmston commented
Ready for a re-review.

2016-09-19 16:07 UTC, lmorchard commented
Will re-review today

2016-09-19 16:14 UTC, lmorchard commented on addon/lib/share-prompt.js
> +    if (reason === 'uninstall') {
Ah, cool, better to move this reason handling here than doing it in index.js

2016-09-19 16:14 UTC, lmorchard approved these changes

2016-09-19 16:32 UTC, merged