[fixes #1337] Add GA to addon
mozilla/testpilot pull request #1359
Opened 2016-09-15 19:27 UTC by ckprice

Couple TODOs

- [ ] replace code with new one from @garethcull for the addon sends.
- [ ] legal review including usage of `store.clientUUID`. Think we may be clear to  use this since we're no longer incorporating FxA.

Fixes #1337.

2016-09-15 21:11 UTC, ckprice commented
I cleared the obvious errors. Looks like Circle starts getting wonky at 

```
console.error: testpilot-addon: 
  Message: Module `@test/options` is not found at resource://gre/modules/commonjs/@test/options.js
  Stack:
    @resource://gre/modules/commonjs/sdk/test/options.js:10:17
```

I tried to rebuild a couple (or more) times, and it looks to get stuck at the same spot.

Looking at other Circle builds, I don't see this module being referenced at all.

2016-09-15 21:49 UTC, dannycoates commented
> Looks like Circle starts getting wonky

@ckprice yeah, you'll need to mock 'request' in `test-metrics.js`

something like:

```js
const mocks = {
  store: {},
  callbacks: MockUtils.callbacks({
    seedrandom: ['seedrandom'],
    Events: ['on', 'off', 'emit'],
    TelemetryController: ['submitExternalPing'],
    AddonManager: ['getAddonByID'],
    // @ckprice ADD THIS
    request: ['post'],
    //
    PrefsService: ['set', 'get']
  })
};

const mockLoader = MockUtils.loader(module, './lib/metrics.js', {
  './node_modules/seedrandom/index.js': mocks.callbacks.seedrandom.seedrandom,
  // @ckprice AND THIS
  'sdk/request': {
    Request: function() {
      return mocks.callbacks.request;
    }
  },
  //
  'sdk/simple-storage': {storage: mocks.store},
  'sdk/system/events': mocks.callbacks.Events,
  'sdk/preferences/service': mocks.callbacks.PrefsService,
  'resource://gre/modules/AddonManager.jsm': {
    AddonManager: mocks.callbacks.AddonManager
  },
  'resource://gre/modules/TelemetryController.jsm': {
    TelemetryController: mocks.callbacks.TelemetryController
  },
  'resource://gre/modules/Services.jsm': {
    Services: {
      startup: {
        getStartupInfo: () => (
          {process: Date.now() - (BROWSER_DURATION * 1000)}
        )
      }
    }
  }
});
```

2016-09-15 22:03 UTC, ckprice commented
> something like:

You mean _exactly like_ - thanks @dannycoates! Tests passed. Working on the TODOs now.

2016-09-19 22:49 UTC, ckprice commented
Met with Elvin and Marshall today, and this has been cleared by legal. Waiting for Gareth on the last TODO.

2016-09-20 23:13 UTC, ckprice commented
Updated with the new tracking code, and rebased. Ready for a review.

I created #1395 to follow-up on this as we need a daily ping as well.

2016-09-21 16:42 UTC, dannycoates commented on addon/test/test-metrics.js
> +    request: ['post'],
`sendGAEvent` is such a simple function that the linter is probably all the testing it needs at the moment, but for completeness we probably ought to write a test case in here for it. Its not a blocker IMO though.

2016-09-21 16:44 UTC, dannycoates commented on addon/index.js
> +  const installedCount = 0;
This shouldn't be `const` if it might change on the next line.

2016-09-21 16:46 UTC, dannycoates commented on addon/index.js
> +  const installedCount = 0;
another option is:
```js
const installedCount = (store.installedAddons) ? Object.keys(store.installedAddons).length : 0;
```

2016-09-21 16:48 UTC, dannycoates requested changes
sooo close :)

2016-09-21 18:15 UTC, ckprice commented on addon/index.js
> +  const installedCount = 0;
Updated - thanks again Danny!

2016-09-21 18:28 UTC, dannycoates approved these changes

2016-09-21 18:28 UTC, merged