[fixes #839] GA refinements
mozilla/testpilot pull request #1531
Opened 2016-10-05 21:41 UTC by ckprice

- explicitly set the `page` param in `pageview` calls ([ref](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews)).
- per recommendation from Peter, modify the action/labels for a few event calls

Fixes #839.

2016-10-06 00:10 UTC, chuckharmston requested changes
This feels like the sort of thing that requires a migration plan. We're basically giving up on all `button click` data before the deploy date. Are we okay doing that?

Also: [better commit message](http://chris.beams.io/posts/git-commit/), please. It's good for someone to at least be able to gain a cursory understanding of what happened by reading the first 50 chars.

2016-10-06 00:17 UTC, ckprice commented
> Are we okay doing that?

Yeah, this was suggested by the team responsible for the reporting (Gareth/Peter). Commit message and title updated.

2016-10-06 00:18 UTC, chuckharmston commented
Would it make sense to run both in parallel for a while, so we don't just start over on data?

2016-10-06 14:36 UTC, ckprice commented
> Would it make sense to run both in parallel for a while, so we don't just start over on data?

The way the events are set up is pretty straight forward, I don't know how much we'd benefit from sending extra pings for a whole sprint. But I've invited that team to comment in this PR.

2016-10-06 20:28 UTC, ckprice commented
Talked to Gareth and he said we shouldn't need the two events in parallel with respect to reporting. I also have a checkin scheduled with him tomorrow to verify stage (assuming this merges today).

2016-10-06 20:51 UTC, chuckharmston approved these changes

2016-10-06 20:53 UTC, chuckharmston commented
Not an r+, but I'm going off for the week and am removing myself as blocker.

2016-10-06 21:46 UTC, ckprice commented
Calling out that this **needs review before merge** even though it's green. Ref: https://github.com/mozilla/testpilot/pull/1531#issuecomment-252085391.

Rebased with updated tests (cool stuff).

More context here http://logs.glob.uno/?c=testpilot#c26783.

2016-10-07 18:40 UTC, dannycoates commented
code LGTM 👍

2016-10-11 14:32 UTC, peterGerman commented
@ckprice, I'm not seeing updated event values appearing for enable experiments in the development environment. 

Can you ping me when they are updated so that I can make changes to our reporting?

2016-10-11 16:50 UTC, ckprice commented
One thing we have in GA is a view for dev, so if we're able to merge this, I can regroup with @peterGerman (who is on the team responsible for running the reports/creating the dashboards) the same day and he can help verify that things look okay before we move to stage (or change things if they have to be changed). Thoughts @chuckharmston?

2016-10-12 14:21 UTC, peterGerman commented
@ckprice lets get a placeholder in the calendar for when you think we'll be
meeting about this.

On Tue, Oct 11, 2016 at 12:50 PM, Cory Price <notifications@github.com>
wrote:

> One thing we have in GA is a view for dev, so if we're able to merge this,
> I can regroup with @peterGerman <https://github.com/peterGerman> (who is
> on the team responsible for running the reports/creating the dashboards)
> the same day and he can help verify that things look okay before we move to
> stage (or change things if they have to be changed). Thoughts
> @chuckharmston <https://github.com/chuckharmston>?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mozilla/testpilot/pull/1531#issuecomment-252975681>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVcPQtXW0PPNZwFiqOYIsfm4JorH-EAOks5qy75ggaJpZM4KPUd6>
> .
>

2016-10-12 17:39 UTC, meandavejustice commented
👍

2016-10-12 22:37 UTC, chuckharmston commented
As I mentioned in IRC, feel free to ship this if you're comfortable losing the data continuity. It will hurt our ability to detect regressions, but that's not a primary concern of our implementation of GA, so feel free to ignore it. Code looks good otherwise.

2016-10-13 14:17 UTC, merged