Change copy on email list confirmation message
mozilla/testpilot pull request #1552
Opened 2016-10-07 16:18 UTC by pdehaan

Fixes #1520

2016-10-07 16:27 UTC, johngruen commented
@pdehaan can you smack a screenshot of your PR in here

2016-10-07 16:27 UTC, lmorchard commented on locales/en-US/app.ftl
> -emailOptInSuccessMessage = When you get a chance, head over to your inbox to verify your email address. Thank you!
Should we change the l10n ID, since the text has changed so much?

2016-10-12 22:31 UTC, chuckharmston requested changes

2016-10-12 22:31 UTC, chuckharmston commented on locales/en-US/app.ftl
> -emailOptInSuccessMessage = When you get a chance, head over to your inbox to verify your email address. Thank you!
Yeah, we should. I think the general rule of thumb would be to change the ID whenever the meaning of the string changes.

2016-10-14 17:23 UTC, pdehaan commented on locales/en-US/app.ftl
> -emailOptInSuccessMessage = When you get a chance, head over to your inbox to verify your email address. Thank you!
@lmorchard @chuckharmston What do we want to change the ID to?
I'm guessing it should still have [at least] the `emailOptIn` prefix, but not sure what the best suffix is for this string.

2016-10-14 20:43 UTC, pdehaan commented
Ref: #1551

2016-10-14 21:38 UTC, pdehaan commented on locales/en-US/app.ftl
> -emailOptInSuccessMessage = When you get a chance, head over to your inbox to verify your email address. Thank you!
From IRC:

> @pdehaan: Any ideas on what you want me to change the l10n ID to for https://github.com/mozilla/testpilot/pull/1552#discussion_r82423186?

> @lmorchard: We don't really have a convention, just that it should change to trigger an update (someday) on Pontoon.
> like add a -1 or -2 to the name or the date or something.
> So like emailOptInSuccessMessage2 - not sure what the gaia folks did, but they ran into a need for this.

2016-10-17 16:08 UTC, lmorchard commented
Aaaand of course now [the EmailDialog test is looking for the old l10n ID `emailOptInSuccessMessage`](https://github.com/mozilla/testpilot/blob/907b205fff1a0463bad6c20096ddb488cfea567e/frontend/test/app/components/EmailDialog-test.js#L80) - so that needs a tweak to `emailOptInSuccessMessage2`

2016-10-19 16:14 UTC, lmorchard commented
Going to close this in favor of PR #1633, where I tweaked the test to pass

2016-10-19 16:14 UTC, closed without merging