reword restart page
mozilla/testpilot pull request #1572
Opened 2016-10-11 12:19 UTC by johngruen

2016-10-11 12:19 UTC, johngruen commented
Fixes #1510

2016-10-11 14:34 UTC, chuckharmston requested changes
Tests are also failing and will need updated.

2016-10-11 14:34 UTC, chuckharmston commented on frontend/src/app/components/Restart.js
> +          </div>
Use an `<img>` or `<picture>` tag here? This is a content image, we shouldn't be hiding it as a background image.

2016-10-11 14:34 UTC, chuckharmston commented on frontend/src/app/components/Restart.js
> -           data-l10n-args={JSON.stringify({ experimentTitle })}
We do [some work](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=experimentTitle) to make `experimentTitle` available here. If we won't use it anymore, let's pull all that out.

2016-10-11 14:34 UTC, chuckharmston commented on locales/en-US/app.ftl
> +restartIntroOne = 1. Restart your browser
We should be putting this in an ordered list rather than putting the bullets here.

2016-10-11 14:34 UTC, chuckharmston commented on locales/en-US/app.ftl
> +restartIntroLead = Preflight checklist
These are different than the strings in the component. They should probably be the same.

2016-10-11 18:43 UTC, johngruen commented
@chuckharmston check it out?

2016-10-12 22:30 UTC, chuckharmston approved these changes
Few more tweaks, but it looks good. I'll approve so you can self-merge once you've addressed them.

2016-10-12 22:30 UTC, chuckharmston commented on frontend/src/app/reducers/addon.js
> +const requireRestart = (state) => {
No need for the parens around `state` if there's only one argument.

2016-10-12 22:30 UTC, chuckharmston commented on frontend/src/app/components/Restart.js
> +            <img src="/static/images/restart-graphic@2x.jpg" width="208px" height="273px"/>
`width` and `height` attributes are unitless.

2016-10-17 17:03 UTC, johngruen commented
Hey @chuckharmston, i did a rebase, so you might want to give this one quick check & merge.

2016-10-19 15:26 UTC, johngruen commented
errr, need to rebase again

2016-10-19 18:54 UTC, lmorchard commented
Rebase looks good, previous approval, so I'll just merge

2016-10-19 18:54 UTC, merged