[wip] Removes Django, Docker (closes #1608).
mozilla/testpilot pull request #1612
Opened 2016-10-13 21:18 UTC by chuckharmston

WIP so you can follow along!

And by "you" I mean "CircleCI".

2016-10-13 22:07 UTC, chuckharmston commented
Updating `gulp-sourcemaps` to 1.7.x per [this advice](https://github.com/floridoo/gulp-sourcemaps/issues/238)

2016-10-13 22:48 UTC, chuckharmston commented
No longer WIP. Build down to 3:11. Ready for review!

2016-10-13 23:16 UTC, pdehaan commented on circle.yml
> +    # - ./bin/circleci/run-integration-tests.shi
*.shi?

2016-10-14 00:22 UTC, dannycoates commented on frontend/tasks/scripts.js
> -const sourcemaps = require('gulp-sourcemaps');
I'd like to see this come back now that upstream is fixed

2016-10-14 15:57 UTC, lmorchard commented
Going to take a look through this today. Should make #1522 way easier too

2016-10-14 17:49 UTC, lmorchard requested changes
:+1: but for 2 things - removing the Dockerhub deployment tasks from `circle.yml` and re-adding the sourcemaps stuff that I assume was fixed with #1614

2016-10-14 17:49 UTC, lmorchard commented on circle.yml
> +    - echo "Skipping integration tests."
:+1: Good to leave that there as a reminder for sure

2016-10-14 17:49 UTC, lmorchard commented on circle.yml
>  deployment:
Docker-dependent stuff below here that will break on merge to master. Should delete the `hub_*` deployment cases, leaving the `static_deployment` bit. 

I'd also change the branch from `development-static` to `master`, which will deploy to testpilot-static.dev.mozaws.net. But, I can follow up on that in #1522

2016-10-14 17:49 UTC, lmorchard commented on frontend/tasks/scripts.js
> -const sourcemaps = require('gulp-sourcemaps');
Does this still need to be removed, or did #1613 & #1614 resolve the issue?

2016-10-15 02:03 UTC, chuckharmston commented
@lmorchard Changes made, build passed.

2016-10-17 15:38 UTC, lmorchard approved these changes

2016-10-17 15:38 UTC, lmorchard commented
💥

2016-10-17 15:38 UTC, merged