Fixes #1682. Add docs for windows users
mozilla/testpilot pull request #1699
Opened 2016-10-27 09:55 UTC by dumptyd

Added development quick start guide for Windows hosts and made some changes to a few files to make testpilot run on all operating systems.
Here are the changes: 

`.eslintrc` : Added `linebreak-style: [0]` option as without that eslint throws error on Windows because Windows uses CRLF as newline and *nix systems use LF. 

`addon/package.json` : Added  `package-win` option for Windows users.

`docs/development/quickstart.md` : Updated quickstart.md

`frontend/tasks/pages.js` : Use `Path.basename` for getting file name from an absolute path instead of `file.path.split('/').pop()` as Windows uses backslashes so the latter only works on *nix systems.

2016-10-27 13:31 UTC, chuckharmston requested changes
This looks great, thanks for the contribution! 👍

2016-10-27 13:31 UTC, chuckharmston commented on docs/development/quickstart.md
> +Test Pilot uses Node.js v6.2.0 for development. You may be able to get by using
Danny updated this file yesterday in ece1ba14c1292c4f9763c7f8b08e7006e3e329d7; you may need to rebase against an updated master.

2016-10-27 13:31 UTC, chuckharmston commented on frontend/tasks/pages.js
> +const Path = require('path');
Since the export of `path` is a module and not a class, we should lowercase it.

2016-10-27 13:31 UTC, chuckharmston commented on frontend/tasks/pages.js
> +    //const filename = file.path.split('/').pop();
No need to comment this out, if there are problems we can always check the commit log to find the previous version.

2016-10-27 13:31 UTC, chuckharmston commented on docs/development/quickstart.md
> +Go back to the previous command prompt window and run
I'm a bit confused at why there are two command prompts here. Does it require admin privileges to add to hosts? Is there an easier way to do that than a new window??

2016-10-27 13:31 UTC, chuckharmston commented on docs/development/quickstart.md
> +Now, open command prompt with admin privileges and run this:
Maybe `open a second command prompt window, this time with` would be clearer?

2016-10-27 13:45 UTC, lmorchard commented
I can also give this a run through, since I have a Windows machine that I hack on at night

2016-10-27 14:54 UTC, dumptyd commented on docs/development/quickstart.md
> +Go back to the previous command prompt window and run
I don't think so. I mean there's `runas` command but it asks for credentials. See [this](http://stackoverflow.com/questions/8249705/how-to-run-an-application-as-run-as-administrator-from-the-command-prompt). 

In my opinion, opening a new window is the easiest way.

2016-10-27 16:43 UTC, dumptyd commented
@chuckharmston  I made the changes. :)

2016-10-27 17:21 UTC, chuckharmston approved these changes

2016-10-27 17:22 UTC, chuckharmston commented
I'll hold off on merging until @lmorchard tries it on Windows, but this looks great. Thanks so much for the contribution @dumptyd!

2016-10-28 19:12 UTC, dannycoates commented on .eslintrc
> +  linebreak-style: [0]
I don't think we should be mixing line break styles in the source. Windows editors _can_ use LF instead of CRLF.

2016-10-28 19:38 UTC, dumptyd commented on .eslintrc
> +  linebreak-style: [0]
I don't know much about this, but I didn't change anything or even open a single file in the editor when I tried running `npm start` the first few times (so there's no chance of the editor accidentally changing LF to CRLF). But eslint kept throwing those errors.

2016-10-28 20:06 UTC, dannycoates commented on .eslintrc
> +  linebreak-style: [0]
Git is probably converting the endings automatically. We can leave this line in for now and fix it later with a `.gitattributes` file.

For reference see https://help.github.com/articles/dealing-with-line-endings/

2016-11-01 18:36 UTC, lmorchard commented
Sorry, this fell off my radar. Finally got around to running this on my windows machine, and all looks good!

2016-11-01 18:36 UTC, merged