[wip] Generate data-l10n-id for dynamic content generated from YAML.
mozilla/testpilot pull request #1708
Opened 2016-10-27 22:25 UTC by chuckharmston

Here's one possible approach to localizing YAML content.

Since we're using Pontoon for localization, it struck me that we didn't need to generate big FTL dumps for each experiment; we could simply have generated L10n IDs. Pontoon should handle the rest.

To invalidation all translations for an experiment, creating or changing the `l10n_version` property will change all the existing IDs. It isn't possible to invalidate a single string, though.

Unlocalized, the page would look like this:

<img width="715" alt="screen shot 2016-10-27 at 5 11 23 pm" src="https://cloud.githubusercontent.com/assets/23885/19787757/17dad382-9c6a-11e6-9432-f2e1171941d0.png">

Not ready for review, just putting up for discussion. Thoughts? @lmorchard @johngruen @ckprice @clouserw

2016-10-28 16:40 UTC, chuckharmston commented
The alternative I was trying to describe is to add a l10n-id field in the YAML for each field. If present, it would be used in the same way that `l10n_version` is used here, but only for that field. The problem is that that's another thing to send over XHR, another piece of state we need to hold, and another thing we need to take into account when looking at changes to the DOM. It would have a noticeable impact on performance.

2016-10-28 16:49 UTC, dannycoates commented
original discussion #1340

2016-10-28 17:11 UTC, dannycoates commented
> The problem is that that's another thing to send over XHR, another piece of state we need to hold, and another thing we need to take into account when looking at changes to the DOM

Seem like that's the price of admission if we don't want to hash the content and be able to change individual fields without invalidating the whole thing.

> It would have a noticeable impact on performance

How much?

2016-10-28 20:11 UTC, chuckharmston commented
Code and PR have been updated to reflect earlier discussions. This is now ready for review.

2016-10-29 00:57 UTC, dannycoates commented
I see how this takes care of populating the `data-l10n-id` attributes, but how are we planning on handling the translation files? Is there going to be like `/locales/en-US/tab-center.ftl` or `/locales/en-US/experiments.ftl`? Also how will we populate the default one, generate it from yaml?

2016-10-29 00:59 UTC, chuckharmston commented
As I understand it, Pontoon will allow anything with the data-l10n-id attribute to be localized, even if it doesn't have an existing in the .ftl.

2016-10-29 01:36 UTC, dannycoates commented
> As I understand it, Pontoon will allow anything with the data-l10n-id attribute to be localized, even if it doesn't have an existing in the .ftl.

Sure, but how do we consume those translations on the site? We have to point to something, right? Like: `<link rel="localization" href="/static/locales/{locale}/app.ftl">` Will all the experiment translations go into `app.ftl`?

2016-10-31 16:19 UTC, lmorchard commented
> Note: when this is merged, we will need to go through Pontoon and translate all the YAML content in English. This will always have to be done for new experiments.

FWIW, what I had in mind for #1340 was to auto-generate an en-us experiments.ftl from the YAML content files using the L10N string IDs - i.e. as a task in gulp. Manual translation in Pontoon would be redundant, because the original content is already localized to en-US.

2016-10-31 16:23 UTC, chuckharmston commented
> FWIW, what I had in mind for #1340 was to auto-generate an en-us experiments.ftl from the YAML content files using the L10N string IDs - i.e. as a task in gulp. Manual translation in Pontoon would be redundant, because the original content is already localized to en-US. 

I don't think there's anything stopping us from doing that.

2016-10-31 16:24 UTC, lmorchard commented
> Sure, but how do we consume those translations on the site? We have to point to something, right? Like: <link rel="localization" href="/static/locales/{locale}/app.ftl"> Will all the experiment translations go into app.ftl?

I think L20N is okay with multiple `<link rel="localization">` references, so I figured we could also have `<link rel="localization" href="/static/locales/{locale}/experiments.ftl">`. How that interacts with Pontoon, though, I'm not sure. That is, would Pontoon commit changes to the appropriate FTL file (`app.ftl` or `experiments.ftl`)

2016-10-31 16:26 UTC, lmorchard commented
> I don't think there's anything stopping us from doing that.

Does that mean you plan to do the gulp task as part of this PR? If not, we should keep #1340 open and plan the gulp task as follow-on work.

2016-10-31 16:40 UTC, chuckharmston commented
> Does that mean you plan to do the gulp task as part of this PR? If not, we should keep #1340 open and plan the gulp task as follow-on work.

I don't have plans for that, no, but nothing here precludes it. I wouldn't want to invest time into anything related to gulp until we've figured out if we even want to keep it (#1463)

2016-10-31 19:52 UTC, lmorchard commented
> I wouldn't want to invest time into anything related to gulp until we've figured out if we even want to keep it 

We're keeping it so far, and we need this l10n stuff before we can really move significantly on Webpack - i.e. this sprint or asap

2016-10-31 20:01 UTC, lmorchard commented
Also FWIW - we do need *something* for the en-US .ftl after merging this PR, because *all* content for experiments gets replaced with l10n IDs when the strings are missing:

![screenshot 2016-10-31 15 59 54](https://cloud.githubusercontent.com/assets/21687/19869566/3ad10962-9f83-11e6-9b97-ba2e9469d408.png)

2016-10-31 20:02 UTC, chuckharmston commented
Yep, covered that in comment 0:

> Note: when this is merged, we will need to go through Pontoon and translate all the YAML content in English. This will always have to be done for new experiments.

2016-10-31 20:16 UTC, lmorchard requested changes
TL;DR: We can't ship this as-is, because all the experiment strings are missing from the en-US locale and L20n just replaces content with l10n-ids. 

So I'd want to see an en-US .ftl file ship along with this PR, ideally generated from the YAML via script or build task. Copying & pasting the content into Pontoon is just a roundabout way to get to the same place, IMO (i.e. an en-US ftl file).

2016-10-31 20:17 UTC, lmorchard commented
> Yep, covered that in comment 0:

Yes, I know. And I'm saying we need to fix that as part of this PR, or in this sprint at the latest.

2016-11-01 19:38 UTC, chuckharmston commented on content-src/experiments/activity-stream.yaml
> -    headline: ' '
Deleted all these empty headlines, which seem to be an artifact from Django.

2016-11-01 19:39 UTC, chuckharmston commented on frontend/src/app/lib/utils.js
> +import { experimentL10nId, l10nId, l10nIdFormat, lookup } from '../../../tasks/util';
In order to reuse this logic in the gulp tasks, I had to move these to their own module that doesn't require babelification. I imported them here for testing and other purposes.

2016-11-01 19:41 UTC, chuckharmston commented on frontend/test/app/containers/ExperimentPage-test.js
> +      title_l10nsuffix: 'foo',
Renamed to `_l10nsuffix` per clouserw request.

2016-11-01 19:44 UTC, chuckharmston commented
Updated to include the FTL generation task. [Example output](https://gist.github.com/chuckharmston/9d78bf95e7082a6b8a7617ad2182dbcf).

This is ready for review again.

2016-11-01 20:19 UTC, dannycoates commented
When reordering a list like contributors, it doesn't look obvious that I'd need to add a suffix to `title` when the text isn't changing.

How do we plan on communicating that changing the order of a list requires adding or changing an `_l10nsuffix` to translated strings within those objects? (just reviewing PRs?)

2016-11-01 20:21 UTC, lmorchard approved these changes
:+1: LGTM! Tests are thorough & pass, all content looks good, code is good. Looks like it needs a rebase, but good to go otherwise

2016-11-01 20:21 UTC, lmorchard commented on frontend/src/index.html
Yeah, I think we realized today that this file doesn't even need to exist :/

2016-11-01 20:23 UTC, chuckharmston commented
> When reordering a list like contributors, it doesn't look obvious that I'd need to add a suffix to title when the text isn't changing.

I'm not really sure. My original PR had the ability to replace the index with a slug of sorts (e.g. contributor name), but there wasn't a reliable way to do that and also generate keys in both the Gulp task and component.

2016-11-01 20:24 UTC, lmorchard commented
Hmm, the reordering concern is interesting, though maybe more a doco issue? 

I had at one point considered using a hash of the original string as l10nID as default suffix, but that seemed possibly fraught with its own issues

2016-11-01 20:26 UTC, lmorchard commented
Also maybe we just try to avoid reordering as much as possible. Say we want to add a contributor and the list was originally in alpha order - just tack the name onto the end and sort on the client side?

2016-11-01 20:27 UTC, merged