Support a fake dev-only experiment for feature QA
mozilla/testpilot pull request #1796
Opened 2016-11-10 21:18 UTC by lmorchard

This turned out a little bit more involved than I'd anticipated, after thinking through localization issues and such. Hopefully this catches things, should let us create fake experiments that a) only get built for local & dev environments and b) never show up in our .ftl files as noise for localizers.

I was also lazy on creating the first fake experiment: I copied min-vid and only changed a few fields. We can tweak the rest as needed to try out features.

- `dev: true` YAML property to mark an experiment as dev-only

- ENABLE_DEV_CONTENT=1 env var to include dev content in build

- Update `npm start` to use dev environment vars

- New dev-example.yaml for a fake experiment

- Localization disabled for dev-only experiments
  - excluded from .ftl string extraction
  - data-l10n-id generation returns null

- onlyLaunchedExperimentSelector selector also excludes dev-only
  experiments on stage & prod - reduntant measure alongside build
  process ENABLE_DEV_CONTENT default

- Test updates

Fixes #1762

2016-11-10 21:22 UTC, lmorchard commented
Oh and you should be able to see the site with and without the dev experiment in your local environment like so:
```bash
# With content, by default
npm start 

# Without content, by customizing env vars to gulp
NODE_ENV=development ENABLE_DEV_CONTENT=0 gulp
```

2016-11-10 23:47 UTC, pdehaan commented on content-src/experiments/dev-example.yaml
> +dev: true
Do we need to add this new key to the experiment template?
https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/template.yaml

2016-11-11 17:38 UTC, chuckharmston commented on bin/circleci/build-frontend.sh
> +    NODE_ENV=production ENABLE_PONTOON=1 ENABLE_DEV_CONTENT=1 npm run static
Yeah, after making a similar comment on #1797, I'm convinced that these should be governed by a single `DEV` flag.

2016-11-11 17:40 UTC, chuckharmston commented on content-src/experiments/dev-example.yaml
> +order: 999
A few things I think we'd want to always be testable:

- `locales`
- `locale_blocklist`
- `locale_grantlist`
- `incompatible`

2016-11-11 17:41 UTC, chuckharmston commented on frontend/tasks/util.js
> +  }
:+1:

2016-11-11 17:42 UTC, chuckharmston commented on frontend/test/app/containers/ExperimentPage-test.js
> +  it('should have l10n IDs for content omitted if the experiment is dev-only', () => {
This is tough to parse. Perhaps `should omit l10n IDs for dev-only content`?

2016-11-11 17:43 UTC, chuckharmston requested changes
Looks good overall!

2016-11-11 19:59 UTC, lmorchard commented on bin/circleci/build-frontend.sh
> +    NODE_ENV=production ENABLE_PONTOON=1 ENABLE_DEV_CONTENT=1 npm run static
I replied over there - tl;dr: local & remote dev environments have enough differences to separate them, and IMO I've found turning these things on/off individually to be handy.

2016-11-11 20:00 UTC, lmorchard commented on frontend/test/app/containers/ExperimentPage-test.js
> +  it('should have l10n IDs for content omitted if the experiment is dev-only', () => {
Made this change

2016-11-11 20:02 UTC, lmorchard commented on content-src/experiments/dev-example.yaml
> +dev: true
Updated commit to add this change

2016-11-11 21:03 UTC, chuckharmston approved these changes
I'm not too far from finishing for the week, but this is close, so I'll approve it. 

![tumblr_li1ocze0gv1qbiz5t](https://cloud.githubusercontent.com/assets/23885/20230124/8c0ad366-a817-11e6-991e-a2e73e0e7a05.gif)

2016-11-14 19:32 UTC, lmorchard commented
Rebased against current master, will merge after tests are green

2016-11-14 19:39 UTC, merged

2016-11-15 14:32 UTC, SoftVision-PaulOiegas commented
Since the fake experiment was deployed on dev and since we have only 2 days left till the stage deploy. Could you guys set a graduation date for it as follows in order to test both the pre-graduation and graduation flows ? Currently it appears as "Just launched".

I was thinking at setting graduation today (Tuesday) around 20:00-21:00 hours your time, to be in 24 hours. This will allow us to test the pre-graduation flow on our Wednesday morning. And the actual graduation flow on Thursday our time until you guys reach the office for Stage deploy.

How does it sounds ?

2016-11-16 00:09 UTC, wresuolc commented
I landed https://github.com/mozilla/testpilot/compare/b4dc5b802960...4836bf7947f8 which should let you see it on -dev