remove all leftover data-hooks
mozilla/testpilot pull request #1934
Opened 2016-12-21 15:34 UTC by chuckharmston

Copying from https://github.com/mozilla/testpilot/pull/1933 to diagnose missing CI.

---

I got really sick of looking at these things. Fixes #1586

NB. There are two places where these stayed in: 
- React uses a data-hook to mount the app
- in the email component, a data-hook is used in a test

2017-01-04 00:30 UTC, jaredhirsch requested changes
Hey @johngruen - Looks good overall. Couple minor things:

First, if we're going to this much trouble to remove data-hooks, I think it makes sense to remove the last two occurrences as well: a selector that React can use to bootstrap the app, and a selector used by a test. I bet that replacing the data-hook with an ID would work in both cases. I do think these last two data-hooks should be removed before landing this PR.

Second, in some cases, I think it'd be good to keep the data-hook's content, just to keep things readable/scannable. Especially when the data-hook was in the topmost node returned by a component, it's just nice to have when scanning the DOM later. I've called out spots where I think this change would help, but because readability is more of a judgment call, consider those comments to be suggestions--feel free to disregard if you don't agree.

Feel free to merge this yourself after making changes, or ping me if you want a followup review. Thanks!

2017-01-04 00:30 UTC, jaredhirsch commented on frontend/src/app/components/EmailDialog.js
> +        {!isFirstPage && <div className="modal">
How about an `id="second-page"` for readability? (I think the ID would help more here than in the first-page case, but for symmetry, might be better to keep or lose both.)

2017-01-04 00:30 UTC, jaredhirsch commented on frontend/src/app/components/EmailDialog.js
> +            <button onClick={e => this.continue(e)} className="button default" data-l10n-id="emailOptInConfirmationClose" data-hook="continue">On to the experiments...</button>
It looks like the data-hook slipped by here. Please remove it.

2017-01-04 00:30 UTC, jaredhirsch commented on frontend/src/app/components/EmailDialog.js
> +        {isFirstPage && <div className="modal feedback-modal modal-bounce-in">
How about an `id="first-page"` for readability?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/components/ExperimentRowCard.js
> +      <Link to={`/experiments/${slug}`} onClick={(evt) => this.openDetailPage(evt)}
`id="show-detail"`?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/components/Header.js
> +        <div>
`id="settings"`?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/containers/ExperimentPage.js
> +        {!hasAddon && <section>
`id="testpilot-promo"`?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/containers/ExperimentPage.js
> +          <div>
`id="details"`?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/containers/HomePageNoAddon.js
> +      <section>
`id="landing-page"`?

2017-01-04 00:30 UTC, 6a68 commented on frontend/src/app/containers/NotFoundPage.js
> +        <div>
`id="not-found-page"`?

2017-01-09 18:22 UTC, johngruen commented
@6a68 yeah good points above. I'll work back through this after we land the various last minute l10n issues today

2017-01-12 15:01 UTC, johngruen commented
@6a68 changes made. Could you give it one more look and merge since i touched a lot of files.

Cheers!

2017-01-13 08:13 UTC, johngruen commented
Rebased!

2017-01-17 18:39 UTC, 6a68 commented
lgtm, merging :+1:

2017-01-17 18:39 UTC, merged