made the user counts request not block rendering
mozilla/testpilot pull request #2184
Opened 2017-02-14 21:58 UTC by dannycoates

This mitigates #1480 wrt the user counts. I'm not sure the best way to test it. I just changed the `usageCountsURL` to something unresolveable to check it.

2017-02-15 19:32 UTC, dannycoates commented
i forgot about the counts returning before experiments case... i can make this better

2017-02-21 19:52 UTC, dannycoates commented
I took a different tack on the async loading race... I made experiments.json get browserified so there is no race.

2017-02-21 19:55 UTC, dannycoates commented on frontend/src/app/store.js
> +import experiments from '../../build/api/experiments.json';
this is where the 🐰🎩 happens

2017-02-23 18:55 UTC, dannycoates commented on bin/circleci/test-frontend.sh
> +npm run content
since the app now uses `experiments.json`directly we need to build it in order to run the tests

2017-02-23 18:55 UTC, dannycoates commented on frontend/src/app/actions/experiments.js
> +        () => ({}))
meh on errors

2017-02-23 21:34 UTC, chuckharmston commented on frontend/src/app/actions/experiments.js
> +        () => ({}))
:| I'm not. This is a really good way to suppress exceptions. Can we add some error handling here?

2017-02-23 22:20 UTC, dannycoates commented on frontend/src/app/actions/experiments.js
> +        () => ({}))
I dunno, error handling here feels excessive. If an error happens should we just not have the counts (like this) or fall back to something else (which can get complicated)? If we reported an error somewhere, who's going to look at it and be able to act on it? Also there's zero error handling in the current code either (not an excuse, but we're not having problems with it either)

That's why I went with 'meh'. If you have ideas for handling it I'm all ears.

2017-02-24 23:06 UTC, 6a68 commented
Ugh, sorry I missed this! Looking now

2017-02-25 01:10 UTC, jaredhirsch requested changes
LGTM, couple minor things to address, then good to land yourself (or ping me to do a final pass + merge)

2017-02-25 01:10 UTC, jaredhirsch commented on frontend/src/app/actions/experiments.js
> +        response => response.json(),
I think you'll want to either check `response.ok`, or, equivalently, check that `response.status` is >= 200 and <300, before proceeding: https://mdn.io/Using_Fetch#Checking_that_the_fetch_was_successful

2017-02-25 01:10 UTC, jaredhirsch commented on frontend/src/app/actions/experiments.js
> +        () => ({}))
Good discussion here. My thoughts:

> If an error happens should we just not have the counts (like this) or fall back to something else (which can get complicated)?

I agree that we should fail gracefully, and continue rendering the page without the counts.

> If we reported an error somewhere, who's going to look at it and be able to act on it? 

If the counts can't be loaded, it might just be a local network error, or it might indicate a busted release. How about [forwarding the error to sentry](https://docs.sentry.io/clients/javascript/integrations/react/#expanded-usage), so Ops can determine if it's a global or local thing?

While you're at it, would you mind also adding a sentry ping in the [`subscribeToBasket` error handler](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App.js#L123)? (Since this is a really nice way to detect problems with other services, I'll probably change #2231 to straight-up replace the `sendBeacon` ping centre call with a `fetch` that forwards network errors to Sentry.)

(Optional) If you're up for getting a little fancy, since I'm suggesting adding a `Raven.captureException` call in two spots, you could centralize that into some kind of app-global network error logging function, or DRY things up by wrapping the `fetch` API in a function that forwards exceptions to Sentry automatically...whatever, your call.

2017-02-25 01:10 UTC, jaredhirsch commented on bin/circleci/test-frontend.sh
> +npm run content
:+1: Worth documenting in the shell script? idk, your call, could be useful

2017-02-28 20:05 UTC, dannycoates commented on frontend/src/app/actions/experiments.js
> +        () => ({}))
Logging is fine but should be worked on as a separate issue (#2253). I'm not going to do it in this PR.

2017-02-28 22:29 UTC, fzzzy commented
Does this mean experiments.json will be synchronously available on page load? That will be fantastic.

2017-02-28 22:31 UTC, fzzzy approved these changes
Stoked about this change. r+

2017-03-01 01:30 UTC, merged