WIP 2364 notify user of missing mozAddonManager
mozilla/testpilot pull request #2474
Opened 2017-05-25 18:24 UTC by fzzzy

2017-05-25 18:37 UTC, pdehaan commented on frontend/src/app/components/View.js
> +      copy = "The version of firefox which is installed is too old. Please upgrade.";
Not sure how user-facing these error messages are, but these should probably be "Firefox" (same w/ "Upgrade firefox" above).

2017-05-25 18:39 UTC, fzzzy commented on frontend/src/app/components/View.js
> +      copy = "The version of firefox which is installed is too old. Please upgrade.";
That's why this pr is a wip :) Some of these messages probably need translation too.

2017-06-02 15:41 UTC, lmorchard commented
Can you add a component unit test for this message? Codecov is sad.

2017-06-08 16:42 UTC, fzzzy commented
@lmorchard I have added test coverage and the coverage diff is now zero.

2017-06-08 16:43 UTC, fzzzy commented
@johngruen Can you please take a look at this PR and decide if the strings I added need rewording?

2017-06-12 17:01 UTC, meandavejustice commented
@fzzzy is localization planned for this?

2017-06-15 19:17 UTC, lmorchard requested changes

2017-06-15 19:17 UTC, lmorchard commented on frontend/src/app/components/View.js
> +    let title = <h1 className="warning">Something is wrong!</h1>;
Yeah, we need some L10n for these strings

2017-06-19 21:28 UTC, lmorchard approved these changes
Works for me! I do wish we had a bit more specific advice about what prefs are missing for dev environments, but just running through the quickstart from beginning to end resolved the warning for me on a fresh profile.

2017-06-19 21:28 UTC, merged