Fix #2482 Remove usage of propTypes and replace with FlowTypes.
mozilla/testpilot pull request #2498
Opened 2017-06-06 15:01 UTC by fzzzy

2017-06-07 16:53 UTC, meandavejustice commented on frontend/src/app/components/LayoutWrapper.js
> +// TODO Port propTypes to FlowTypes for LayoutWrapper
noting todo here

2017-06-07 16:58 UTC, meandavejustice requested changes

2017-06-07 16:58 UTC, meandavejustice commented on frontend/src/app/components/LayoutWrapper.js
> +// TODO Port propTypes to FlowTypes for LayoutWrapper
noting todo here

2017-06-07 16:58 UTC, meandavejustice commented on frontend/src/app/components/View.js
> +
noting todo

2017-06-07 16:58 UTC, meandavejustice commented on frontend/src/app/containers/ExperimentPage.js
> +// ExperimentPage.propTypes = {
todo

2017-06-07 20:10 UTC, lmorchard commented
Are flow type checks run in CircleCI? I tried this and got an error:
```bash
Les Orchard@Preciso MINGW32 ~/devel/testpilot
$ ./node_modules/.bin/flow frontend
Launching Flow server for C:\Users\Les Orchard\devel\testpilot\frontend
Spawned flow server (pid=27580)
Logs will go to C:\Users\LESORC~1\AppData\Local\Temp\flow\CzCzBUserszBLes OrchardzBdevelzBtestpilotzBfrontend.log
Launching Flow server for C:\Users\Les Orchard\devel\testpilot\frontend
Spawned flow server (pid=3656)
Logs will go to C:\Users\LESORC~1\AppData\Local\Temp\flow\CzCzBUserszBLes OrchardzBdevelzBtestpilotzBfrontend.log
frontend/src/app/components/ExperimentTourDialog.js:33
 33:     const { experiment, isExperimentEnabled } = this.props;
                             ^^^^^^^^^^^^^^^^^^^ property `isExperimentEnabled`. Property not found in
 33:     const { experiment, isExperimentEnabled } = this.props;
                                                     ^^^^^^^^^^ object type


Found 1 error
```

2017-06-07 20:11 UTC, lmorchard commented
Looked simple enough to fix, though the error should probably be cause to fail the CircleCI run.
```
Les Orchard@Preciso MINGW32 ~/devel/testpilot
$ git diff
diff --git a/frontend/src/app/components/ExperimentTourDialog.js b/frontend/src/app/components/ExperimentTourDialog.js
index a5cc5f8c..2d385f72 100644
--- a/frontend/src/app/components/ExperimentTourDialog.js
+++ b/frontend/src/app/components/ExperimentTourDialog.js
@@ -7,6 +7,7 @@ import { experimentL10nId } from '../lib/utils';

 type ExperimentTourDialogProps = {
   experiment: Object,
+  isExperimentEnabled: Function,
   onCancel: Function,
   onComplete: Function,
   sendToGA: Function
```

2017-06-07 20:14 UTC, lmorchard commented
Maybe this tweak is enough to make this happen on CircleCI?

```patch
diff --git a/package.json b/package.json
index b9e8801d..28a8d1f3 100644
--- a/package.json
+++ b/package.json
@@ -114,7 +114,7 @@
     "static": "gulp dist-build",
     "docs": "doctoc README.md && doctoc addon/README.md",
     "lint": "gulp scripts-lint styles-lint",
-    "test": "cd frontend && mocha --require babel-register --require test-setup.js --recursive",
+    "test": "cd frontend && flow && mocha --require babel-register --require test-setup.js --recursive",
     "test:ci": "cross-env NODE_ENV=test nyc mocha --recursive --reporter mocha-junit-reporter --require frontend/test-setup.js frontend/test",
     "test:watch": "npm test -- --watch",
     "test:all": "npm run lint && npm run test && npm run flow-coverage && cd addon && npm run lint && npm run coverage && npm run test",
```

2017-06-07 20:22 UTC, lmorchard commented
Still soaking my head in Flow, so this is kind of a conceptual question: 

We do a lot of things in the pattern of `<SubComponent {...this.props}>` to pass along psuedo-global context from the `<App>` component. We'd get a warning from dev-mode React at run time if those props were missing something. 

Does Flow catch this for us at validation time? I guess I could try breaking something locally and see what happens.

2017-06-07 21:26 UTC, fzzzy commented
@lmorchard I'm surprised that circle wasn't running the flow tests, but it seems to have been missing. Good catch, thanks.

About your question re: `...props`, I do think flow tracks that properly. However, it seems to not understand what is happening with react-redux and the components that get their props directly from the App. That's what I put the TODOs there for. I need to learn how to handle that case.

@meandavejustice The TODOs are there because I don't yet know how to handle those cases. Currently HEAD is broken if you do a fresh checkout because the propTypes warnings turned into errors. I'm not able to update our dependencies until we either remove propTypes or switch to the standalone propTypes module. So, I'd prefer if we get HEAD sorted out so it is not busted, and fix the TODOs later.

2017-06-07 22:03 UTC, fzzzy commented
Good, I was able to get flow to fail on circleci.

2017-06-07 22:33 UTC, fzzzy commented
I filed https://github.com/mozilla/testpilot/issues/2504 to take care of the TODOs.

2017-06-07 22:33 UTC, meandavejustice approved these changes

2017-06-07 22:34 UTC, merged

2017-06-08 14:19 UTC, lmorchard commented
Can we squash stuff like this before merging? (eg. the "letr's see" commits?)

2017-06-08 15:01 UTC, fzzzy commented
@lmorchard Yep, sorry about that.

2017-06-08 15:09 UTC, fzzzy commented
The one thing I wish is that squashing wouldn't ruin the interleaving of commits and comments. Maybe github will figure out how to fix that some day, though.