Temporarily remove integration tests until stabilized/sped up (connected to #2536).
mozilla/testpilot pull request #2541
Opened 2017-06-20 19:12 UTC by chuckharmston

I had [another build](https://circleci.com/gh/mozilla/testpilot/4543) take 20 minutes before timing out. Let's pull back these tests until they're quicker and more stable.

2017-06-20 19:29 UTC, lmorchard requested changes

2017-06-20 19:29 UTC, lmorchard commented on circle.yml
> -    - sh ./bin/circleci/test-firefox-release.sh
We have a history of turning integration tests off and forgetting about them. Should at least leave the tests for Firefox release enabled and plan to improve things to the point where we can turn the other two back on.

2017-06-20 21:29 UTC, chuckharmston commented on circle.yml
> -    - sh ./bin/circleci/test-firefox-release.sh
I'd agree with you if build time was the only concern, but these are causing builds to intermittently fail, and idempotency is an important quality of a good test suite.

2017-06-21 00:12 UTC, jrbenny35 commented
IDK if you saw my comment on the issue but I have parallel tests working. I just need to figure out the impact on the entire mozilla organizations use of containers and such.

https://circleci.com/gh/jrbenny35/testpilot/200#tests/containers/0

2017-06-21 14:10 UTC, lmorchard commented
Alright, let's do this: I just started a branch [restore-integration-tests](https://github.com/mozilla/testpilot/tree/restore-integration-tests). Going to merge this PR to try to resolve the timeouts we're seeing, but then start a PR immediately from that branch so we're nagged to fix this. And CircleCI tests will run from that branch as we hopefully throw work at it to improve things per issue #2536

2017-06-21 14:10 UTC, merged