use context fill for webext icon
mozilla/testpilot pull request #2776
Opened 2017-08-14 13:17 UTC by johngruen

@lmorchard I adjusted the webextension manifest so we can use `context-fill` for the test pilot icon and inherit the standard toolbar icon color for a given theme. 

I basically copied what we did here:

2017-08-14 13:20 UTC, johngruen commented
Also i tested this by using  `web-ext run --firefox=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin` from the `addon/build/webextnsion` directory after running `npm run package:dev`. I couldn't figure out how to build and run the bootstrapped add-on on Nightly, which is the only place the necessary in-tree changes have landed thus far.

2017-08-14 13:31 UTC, johngruen commented
Fixes #2602 as well

2017-08-14 13:31 UTC, johngruen commented
Also, not sure what our versioning scheme is on the add-on, but this may require a version bump.

2017-08-14 18:37 UTC, lmorchard commented
If you ran `npm run package:dev`, that should give you an XPI that you can try with about:debugging. That, or [following the dev setup here](https://github.com/mozilla/testpilot/tree/master/addon#building-and-development) can get you running with a file watcher.

It's not a webextension, so loading it with `web-ext run` won't work.

2017-08-14 19:52 UTC, lmorchard requested changes
Hmm looks like [we need a new pref to get the unsigned add-on installed on Nightly](https://github.com/mozilla/testpilot/pull/2779): extensions.legacy.enabled = true

Did that, ran `npm run package:dev` and installed the XPI with `about:debugging`. Looks like the icon is the inverse of what we want it to be on light & dark themes

2017-08-14 19:52 UTC, lmorchard commented on addon/src/webextension/icons/icon-16.svg
> +<svg width="16" height="14" viewBox="0 0 16 14" xmlns="http://www.w3.org/2000/svg"><path fill="context-fill" d="M14.962 6.169c.51.253.865.738.954 1.3.092.83-.476 1.884-1.51 2.85.48 1.481 1.027 3.681.
I'm not really sure what context-fill does, but it seems to be working in reverse from what's intended:

* Default theme: 
  ![capture2](https://user-images.githubusercontent.com/21687/29288819-392d5d9c-8108-11e7-91d5-e278e59fad1d.PNG)
* Light compact theme: 
  ![capture3](https://user-images.githubusercontent.com/21687/29288823-41329570-8108-11e7-8955-6fa8e5c3d151.PNG)
* Dark compact theme: 
  ![capture4](https://user-images.githubusercontent.com/21687/29288831-499dea16-8108-11e7-875f-9099e2760277.PNG)

2017-08-14 19:57 UTC, johngruen commented on addon/src/webextension/icons/icon-16.svg
> +<svg width="16" height="14" viewBox="0 0 16 14" xmlns="http://www.w3.org/2000/svg"><path fill="context-fill" d="M14.962 6.169c.51.253.865.738.954 1.3.092.83-.476 1.884-1.51 2.85.48 1.481 1.027 3.681.
@lmorchard i don't think the svg would have that drop shadow, are you sure you're looking at the version w/ the svg icon? I can verify later

2017-08-14 20:49 UTC, lmorchard commented on addon/src/webextension/icons/icon-16.svg
> +<svg width="16" height="14" viewBox="0 0 16 14" xmlns="http://www.w3.org/2000/svg"><path fill="context-fill" d="M14.962 6.169c.51.253.865.738.954 1.3.092.83-.476 1.884-1.51 2.85.48 1.481 1.027 3.681.
Hmm, not sure what happened... I restarted and now it works fine when I install via about:debugging. So, mainly just needs a version bump I think

2017-08-15 14:40 UTC, johngruen commented on addon/package.json
> +  "version": "2.0.3",
@lmorchard i bumped the version in three places which seems not good, but maybe that's how it's done

2017-08-15 14:49 UTC, lmorchard commented on addon/package.json
> +  "version": "2.0.3",
No, you only change it in package.json. The webpack copies that version over to install.rdf and manifest.json

2017-08-15 15:56 UTC, lmorchard approved these changes

2017-08-15 15:57 UTC, lmorchard commented
Doesn't hurt anything to change the version in all three spots, but we don't need to do that in the future. Will just merge though

2017-08-15 15:57 UTC, merged