Added install and enable tests - part 2
mozilla/testpilot pull request #2790
Opened 2017-08-17 16:21 UTC by jrbenny35

Found a bug in our old test setup that caused some weird hangs during the CI runs.

2017-08-17 16:23 UTC, chuckharmston commented
@jrbenny35 would you mind adding info about what the bug was and why this fixed it?

2017-08-17 16:29 UTC, jrbenny35 commented
> would you mind adding info about what the bug was and why this fixed it?

Sure, I didn't track it down too much but I think it was circle ci caching. I don't think it was a problem with the script files. That's why there were so many commits. 

I guess saying there was a bug with the test setup would be incorrect, more so, a quirk of circleci and how the new tests were being set up.

2017-08-17 17:56 UTC, fzzzy requested changes
I just have some questions about the diff to clarify my own understanding. Thanks.

2017-08-17 17:56 UTC, fzzzy commented on circle.yml
> +    - # "/home/ubuntu/firefox-downloads"
I'm not super familiar with yaml -- what does this do? Exclude it from the list? Can we just delete the line instead?

2017-08-17 17:56 UTC, fzzzy commented on circle.yml
> +    - # ./bin/circleci/test-firefox-dev.sh
Same here, can we just delete this?

2017-08-17 17:56 UTC, fzzzy commented on frontend/test/ui/conftest.py
> +def enable_dev_experiment():
This isn't called anywhere. I can kind of guess that the decorator automatically applies it, but can you clarify?

scope='session' means that it gets run once per session, and autouse means it gets used?

Does the code before the yield run at the beginning of the session, and the code after the yield run at the end of the session?

2017-08-17 17:56 UTC, fzzzy commented on frontend/test/ui/requirements/requirements.txt
> +pytest==3.2.0
Is this intentional? What's the reason for the downgrade?

2017-08-17 17:56 UTC, fzzzy commented on frontend/test/ui/test_install.py
> +@pytest.mark.skipif(os.environ.get('SKIP_INSTALL_TEST') is not None,
Is there a technical reason for this skip?

2017-08-17 17:58 UTC, jrbenny35 commented on circle.yml
> +    - # "/home/ubuntu/firefox-downloads"
I can remove this back to how it was. Nightly had a bug last week that caused it to not read the capabilities given to it by geckodriver.

2017-08-17 17:58 UTC, jrbenny35 commented on circle.yml
> +    - # ./bin/circleci/test-firefox-dev.sh
So just leave release and nightly?

2017-08-17 17:58 UTC, jrbenny35 commented on frontend/test/ui/conftest.py
> +def enable_dev_experiment():
You are 100% correct.

2017-08-17 17:59 UTC, b4handjr commented on frontend/test/ui/requirements/requirements.txt
> +pytest==3.2.0
This wasn't intentional.

2017-08-17 18:00 UTC, jrbenny35 commented on frontend/test/ui/test_install.py
> +@pytest.mark.skipif(os.environ.get('SKIP_INSTALL_TEST') is not None,
Yes so the preference ```xpinstall.signatures.required', False``` cannot be set in firefox release or beta, but only dev and nightly. Currently dev, is being shipped as beta it seems, so this skips the install tests on release but runs them on nightly.

2017-08-17 19:09 UTC, fzzzy commented on circle.yml
> +    - # "/home/ubuntu/firefox-downloads"
Please do.

2017-08-17 19:09 UTC, fzzzy commented on circle.yml
> +    - # ./bin/circleci/test-firefox-dev.sh
I think release and nightly are good enough.

2017-08-17 19:10 UTC, fzzzy commented on frontend/test/ui/test_install.py
> +@pytest.mark.skipif(os.environ.get('SKIP_INSTALL_TEST') is not None,
Ok, great info, thanks.

2017-08-28 21:22 UTC, jrbenny35 commented
@fzzzy Am I missing something?

2017-08-28 22:02 UTC, fzzzy commented
@jrbenny35 Please squash it. Also it looks like the tests failed on the last commit.

2017-08-28 22:02 UTC, fzzzy commented
Oh, it has conflicts, so it needs rebasing.

2017-08-28 22:38 UTC, jrbenny35 commented
Should be good now!

2017-08-28 22:43 UTC, merged

2017-08-29 12:11 UTC, fzzzy commented
Although the tests pass on this, once it is merged to master, the script which deploys to dev breaks in a strange way. I'm going to revert this until we figure out what is going on there.