Photonize wordmark
mozilla/testpilot pull request #2989
Opened 2017-10-26 00:35 UTC by johngruen

Fixes #2971 

DO NOT MERGE UNTIL AFTER Milestone 34 is tagged!

2017-10-26 05:42 UTC, flodolo commented on locales/en-US/app.ftl
> +jsDisabledWarning = Test Pilot requires JavaScript. Sorry about that.
Looks like this one sneaked in from another PR

2017-10-30 18:24 UTC, johngruen commented
@lmorchard this should be ready to go now

2017-10-31 21:12 UTC, meandavejustice commented
This seems to introduce an issue at smaller resolutions where part of the Firefox logo is repeating and being cut off to the right of the text.
BEFORE:
![2017-10-31--10-17-23-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32249175-6c82beba-be5e-11e7-894c-25fa8f930b03.png)
AFTER:
![2017-10-31--09-17-53-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32249181-71e7a488-be5e-11e7-8013-1033b641025c.png)

2017-10-31 21:13 UTC, meandavejustice requested changes

2017-10-31 21:13 UTC, meandavejustice commented on frontend/src/styles/modules/_main-header.scss
> +      background-repeat: none;
Seems weird that the logo seems to be still showing up again in the lower resolution(mobile) view when `background-repeat` is set here.. hmmm

2017-11-01 02:26 UTC, johngruen commented
@meandavejustice put `none` instead of `no-repeat`

2017-11-03 19:52 UTC, lmorchard commented
Looks :100: to me now

2017-11-03 19:52 UTC, merged