[WIP] Fixed "More Experiments" button at the bottom of home pages
mozilla/testpilot pull request #3289
Opened 2018-01-24 21:13 UTC by lmorchard

- Add "More Experiments" button to bottom of landing pages that links to
  list of experiments, hides itself when the experiments are visible

- Create Visibility component with dive that changes classname when the
  user has scrolled down or past it

- Move HomePage container and associated components into a bundle
  directory - can now add an index.css for the More Experiments button
  and associated image

- Small tweak for path globbing to make `npm test` work on Windows
  PowerShell (should work in *nix too)

Fixes #3001

2018-01-24 21:19 UTC, lmorchard commented
Work in progress, insofar as [it probably needs a better icon for the button](https://github.com/mozilla/testpilot/issues/3001#issuecomment-359597774). Could probably also use a CSS animation when it appears/disappears, but I didn't quite get that to work with opacity and display: none and could use an assist there

2018-01-24 21:22 UTC, lmorchard commented
Oh yeah, and I need to add l10n for the "More Experiments" text!

2018-01-24 21:25 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3289/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/a9b0e3cdea6d91f362c590b171314e8852fcf49f/

2018-01-24 21:34 UTC, lmorchard commented
Huh. Not sure why integration tests failed, will take a look today or tomorrow

2018-01-24 21:34 UTC, lmorchard commented
Also, [here's a more specific link to the story demoing the header](http://testpilot-storybook.dev.mozaws.net/a9b0e3cdea6d91f362c590b171314e8852fcf49f/?selectedKind=HomePage&selectedStory=Fixed%20off-screen%20subtitle&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

2018-01-31 21:26 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3289/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/72db535110ccbd95ed215eb09d67e5e08744301f/

2018-01-31 21:46 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3289/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/72db535110ccbd95ed215eb09d67e5e08744301f/

2018-01-31 22:04 UTC, lmorchard commented
Finally got the integration test to pass, dropping the [WIP]

2018-01-31 22:33 UTC, meandavejustice commented
@lmorchard This doesn't seem to have the animation from https://github.com/mozilla/testpilot/issues/3001#issuecomment-360345885

2018-01-31 22:35 UTC, meandavejustice requested changes
Still missing animation from https://github.com/mozilla/testpilot/issues/3001#issuecomment-360345885 https://codepen.io/youwenliang/pen/qpzOqo

2018-01-31 22:35 UTC, meandavejustice commented on frontend/src/app/containers/HomePage/index.scss
> +.landingExperiments {
Missing animation from https://github.com/mozilla/testpilot/issues/3001#issuecomment-360345885

2018-01-31 22:49 UTC, lmorchard commented
> This doesn't seem to have the animation from #3001 (comment)

Yeah, [like I said](https://github.com/mozilla/testpilot/pull/3289#issuecomment-360276816), the animation is not available from UX

2018-02-01 20:18 UTC, lmorchard commented
Added the button animation and a string to localize for the "More Experiments" label

2018-02-01 20:23 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3289/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2baade5afd9f0dee7e30ed875867dd98dce73850/

2018-02-01 21:28 UTC, lmorchard commented
Transient failure in integration test, failed to download Firefox. Re-running.

2018-02-01 21:34 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3289/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2baade5afd9f0dee7e30ed875867dd98dce73850/

2018-02-02 15:12 UTC, SoftVision-PaulOiegas commented
@lmorchard is there a way that we could generate the Storybook links to open the exact thing that was implemented? We always click on them and they lead us to the first page (Banner > Big Banner). We need to use the search field to find out what changed and we cannot find it every time...

2018-02-02 18:45 UTC, meandavejustice approved these changes

2018-02-02 19:02 UTC, lmorchard commented
>  is there a way that we could generate the Storybook links to open the exact thing that was implemented?

Not automatically, no - there's not really a way to tell what's changed. That's why I [pasted in a link to it earlier](https://github.com/mozilla/testpilot/pull/3289#issuecomment-360281117), but of course that changes after a few storybook deployments. You could copy the query string params and paste them onto a new deployment URL though

2018-02-02 19:27 UTC, merged