add grad warning strings for experiments
mozilla/testpilot pull request #3353
Opened 2018-02-15 20:09 UTC by johngruen

We need to merge this after we tag for l10n, also the cliqz string is pending signoff from Javaun.

2018-02-15 20:12 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3353/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/70d26346e10abc1f109fe0c78a9ded0b257b61d1/

2018-02-15 21:24 UTC, clouserw approved these changes

2018-02-16 01:47 UTC, pdehaan commented on content-src/experiments/snooze-tabs.yaml
> +graduation_url: http://example.com/graduation-report
Do we want the fake `graduation_url` here (it isn't in **cliqz**, **min vid**, or **voice fill**.

2018-02-16 14:21 UTC, johngruen commented on content-src/experiments/snooze-tabs.yaml
> +graduation_url: http://example.com/graduation-report
@pdehaan doesn't block...we'll have to do a separate PR either way

2018-02-16 16:20 UTC, SoftVision-PaulOiegas commented
Find the experiments graduation decisions by spying the PR code. 😆 That's one way QA can find out what will happen with each experiment. 

![giphy](https://user-images.githubusercontent.com/17258026/36317532-0341f604-1346-11e8-98de-9895c5432c1f.gif)

2018-02-20 16:30 UTC, chuckharmston requested changes
Small grammar nit.

2018-02-20 16:30 UTC, chuckharmston commented on content-src/experiments/min-vid.yaml
> +eol_warning: Min Vid is leaving Test Pilot soon, and unfortunately, we will be disabling it for all users.
I don't think the second comma here is necessary.

2018-02-20 16:31 UTC, chuckharmston commented
Ping @flodolo for review on these substantial string changes.

2018-02-20 16:50 UTC, flodolo approved these changes
No issues on my side

2018-02-20 17:57 UTC, chuckharmston approved these changes

2018-02-20 17:59 UTC, merged

2018-02-20 18:03 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3353/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/d5656c05ae5664798a22a8e2f115396636499869/

2018-02-20 18:04 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3353/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/180e2b17332ab73a4e2c147111b6b5298efc6410/