removed addon polling
mozilla/testpilot pull request #3425
Opened 2018-03-16 18:57 UTC by dannycoates

see #3123 
fixes #3264

2018-03-16 19:00 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/3b00adeb6b9c091e1e3a78a7e79e2e85cc3366da/

2018-03-16 19:30 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/e1e5418ae76a10a30c2e6636748437ab61da040f/

2018-03-16 22:32 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/12b7f2936e5a13fa416921b6310a58f51aa1d7e1/

2018-03-16 22:45 UTC, dannycoates commented on frontend/src/app/containers/App/index.js
> -    this.props.setHasAddon(!!window.navigator.testpilotAddon);
I started to pull this thread... "Can I remove this line?" and wound up unraveling the rest of addon and browser initialization. It turns out `shouldShowUpgradeWarning` relies on a set of assumptions that came unglued when `hasAddon` doesn't start out as null. Anyway, the browser state is static once initialized, so I moved it into the initial state, which saves a lap around the event loop and also ensure the rest of the conditions for `shouldShowUpgradeWarning` are in sync.

2018-03-16 22:48 UTC, dannycoates commented on frontend/src/app/reducers/browser.js
> -// @flow
`navigator.mozAddonManager` below is breaking flow

2018-03-16 22:50 UTC, dannycoates commented on frontend/src/app/lib/InstallManager.js
> +    store.dispatch(addonActions.setHasAddon(!!addon));
this replaces the need for `navigator.testpilotAddon`... i think

2018-03-16 22:53 UTC, dannycoates commented on frontend/src/app/lib/InstallManager.js
> +    if (!addon) { return false; }
most all the changes in this file come straight from #3123

2018-03-19 19:09 UTC, meandavejustice requested changes
This is my only comment for now

2018-03-19 19:09 UTC, meandavejustice commented on frontend/src/app/lib/InstallManager.js
> +    const { experiments } = store.getState();
This loop looks like a duplicate of line 97 above, can they be consolidated into a function?

2018-03-19 20:21 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/54dd68244589ecbd6cdaaebc211d2829ce375ba2/

2018-03-19 20:23 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/6c0bd61be30e999933f3ecef21ee009a8af3542c/

2018-03-19 20:29 UTC, dannycoates commented
@meandavejustice updated

2018-03-20 01:06 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3425/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/c5cfb013ad0ca3beb2c5504e40107e4eb2102405/

2018-03-20 16:22 UTC, merged