Remove traces of restartRequired
mozilla/testpilot pull request #3691
Opened 2018-07-03 19:00 UTC by Vimal-Raghubir

As indicated in the commit messages, these portions of code were removed since restartRequired is not needed anymore. The issue that indicated this required fix is #3571.

2018-07-05 19:42 UTC, lmorchard commented on frontend/src/app/containers/App/index.js
> -import RestartPage from "../RestartPage";
Since the `RestartPage` container is no longer used, it should be removed from the project too

2018-07-05 21:59 UTC, fzzzy commented
I'll take a look at this tomorrow.

2018-07-16 18:33 UTC, fzzzy commented
@Vimal-Raghubir Thanks, this looks good, but there are conflicts now. Can you please pull from master into your branch, fix the conflicts, and push to your branch? You could also rebase the branch if you know how to do that and prefer that.

2018-07-25 17:19 UTC, fzzzy requested changes
Conflicts need resolving.

2018-08-01 17:02 UTC, merged