add apt-get update to install-test-deps script
mozilla/testpilot pull request #3814
Opened 2018-08-22 21:19 UTC by meandavejustice

2018-08-22 21:25 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3814/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/ad874937d95755f45ceda2aa3e8bbbda5dbeda09/

2018-08-22 21:35 UTC, jrbenny35 commented
Can we re-enable the tests in the circle.yml?

2018-08-22 22:06 UTC, fzzzy commented
Yes, let's re-enable the integration tests in this pr before merging it.

2018-08-23 11:18 UTC, fzzzy commented
While we are at it, let's also disable the intermittent newsletter form test so that hopefully the integration tests pass more reliably going forward.

2018-08-23 11:26 UTC, fzzzy requested changes
Please re-enable the integration tests and disable the intermittent newsletter form test in this branch.

2018-08-23 13:18 UTC, b4handjr commented
> While we are at it, let's also disable the intermittent newsletter form test so that hopefully the integration tests pass more reliably going forward.

Which test is that exactly?

2018-08-23 16:31 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3814/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/3c01c8874ee95813138b5266d23a79d834df1664/

2018-08-23 16:43 UTC, MozillaTestPilotStorybook commented
# Storybook Deployment
Pull Request: http://testpilot-storybook.dev.mozaws.net/pull/3814/index.html
Commit: http://testpilot-storybook.dev.mozaws.net/2b36f68c7cfc6f4cea575ed59ddda25149fa2693/

2018-08-23 17:23 UTC, b4handjr requested changes

2018-08-23 17:23 UTC, b4handjr commented on frontend/test/ui/test_homepage.py
> +# @pytest.mark.nondestructive
Just use this: https://docs.pytest.org/en/latest/skipping.html#skipping-test-functions

2018-08-23 17:24 UTC, b4handjr commented on frontend/test/ui/test_homepage.py
> +# @pytest.mark.nondestructive
A reason why other than "Its flaky" would be good too as I'd like to fix it.

2018-08-23 20:38 UTC, fzzzy requested changes

2018-08-23 20:38 UTC, fzzzy commented on circle.yml
> +      - storybook_deploy:
We have to disable the storybook deploy for now until we have cycles to work on it.

2018-08-23 20:39 UTC, fzzzy commented on frontend/test/ui/test_homepage.py
> +# @pytest.mark.nondestructive
@jrbenny35 you can look through the circle history to see it failing intermittently. it is unable to find the element on the page even though it is there.

2018-08-23 20:45 UTC, b4handjr requested changes

2018-08-23 20:45 UTC, jrbenny35 commented on frontend/test/ui/test_homepage.py
> +@pytest.mark.skip(reason="Test is really inconsistent, hard to
I think you need to do a ```\``` so the string extends to the next line.

2018-08-23 21:14 UTC, b4handjr approved these changes

2018-08-23 21:21 UTC, fzzzy approved these changes

2018-08-23 21:21 UTC, merged