Fixes #3061: Firefox Free Download button shows animation when hovered
mozilla/testpilot pull request #3838
Opened 2018-08-30 10:55 UTC by ShivangiKakkar

## Fixes #3061 
### BEFORE:
Button before adding animaton looked like [this](https://drive.google.com/open?id=1qy_8n3HKuvjc32ZCHhdGUrZHVYUv7oRQ)
### AFTER:
Button after adding animation looked like [this](https://drive.google.com/open?id=13fu2U1TIf12mfPswnD66Kv35uj2T-kFX)
### DESCRIPTION: 
- I added a new css class `&:hover .main-install__badge` inside the `.main-install__download` class to apply animation to the `badge` when download button is being hovered.
- The animation specifications are taken from [this](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard0) file, please let me know if you think I need to change something in it.

2018-08-30 11:31 UTC, ShivangiKakkar commented
Hey! @SoftVision-PaulOiegas @meandavejustice @johngruen 
We need to decide on this in order to close the issue. [this](https://github.com/mozilla/testpilot/pull/3819#issuecomment-415785237)

2018-09-05 17:07 UTC, meandavejustice commented
Hey @youwenliang would you mind giving this a look?

2018-09-18 20:29 UTC, ShivangiKakkar commented
@meandavejustice Any updates on this :)

2018-09-19 16:14 UTC, meandavejustice commented
@ShivangiKakkar I'm having @youwenliang take a look, he's been busy past couple weeks. Sorry for the delay

2018-09-19 16:21 UTC, ShivangiKakkar commented
@meandavejustice No problem, was just reminding you. :)

2018-09-20 02:56 UTC, youwenliang requested changes

2018-09-20 02:56 UTC, youwenliang commented on frontend/src/app/components/MainInstallButton/index.scss
> +    animation: bounce 0.15s infinite alternate;
I would change 0.15s to 0.4s so that it looks more subtle. Other than that it's all good.

2018-09-20 02:57 UTC, youwenliang commented
> @meandavejustice No problem, was just reminding you. :)

Sorry I made that comment about animation timing last week but didn't submit the review...

2018-09-20 05:10 UTC, ShivangiKakkar commented
@youwenliang No problem :)

2018-09-20 07:18 UTC, ShivangiKakkar commented
@meandavejustice @youwenliang Please review again :)

2018-09-20 07:37 UTC, youwenliang commented
Looks good to me.

2018-09-20 22:17 UTC, merged